- name: Install necessary packages and dependencies
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['python3-pip']
        state: present

- name: Install MicroK8s
  hosts: all
  become: true
  tasks:
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s via snap
      command: snap install microk8s --classic --channel=1.20

    - name: Add current user to MicroK8s group
      command: usermod -a -G microk8s $USER

    - name: Allow MicroK8s commands without sudo
      command: sudo snap alias microk8s.kubectl kubectl
      args:
        creates: /usr/local/bin/kubectl

- name: Reboot the instance to apply changes
  hosts: all
  become: true
  tasks:
    - name: Reboot the instance
      command: reboot
      async: 0
      poll: 0
