- name: Configure EC2 Instance
  hosts: all
  become: true
  vars:
    microk8s_version: "1.27"
  tasks:
    # ... existing tasks to update apt cache, install Docker, etc ...

    - name: Install MicroK8s
      shell: |
        snap install microk8s --classic --channel={{ microk8s_version }}
        usermod -a -G microk8s ubuntu
      environment:
        HOME: /home/ubuntu

    - name: Wait for MicroK8s to start
      shell: microk8s.status --wait-ready
      environment:
        HOME: /home/ubuntu

    - name: Enable MicroK8s addons
      shell: microk8s.enable dns storage ingress
      environment:
        HOME: /home/ubuntu

    - name: Add kubectl alias and grant permissions for .kube directory
      lineinfile:
        dest: /home/ubuntu/.bash_aliases
        line: "alias kubectl='microk8s kubectl'"
      become_user: ubuntu

- name: Deploy SonarQube
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install Helm
      apt:
        name: ['helm']
        state: present

    - name: Add SonarQube Helm repository
      shell: helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube

    - name: Upgrade or Install SonarQube
      shell: helm upgrade --install sonarqube sonarqube/sonarqube --set sonar.web.port=80 --set sonar.web.context=/ --set sonar.web.javaOpts="-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError" --set postgresql.postgresqlUsername=sonar --set postgresql.postgresqlPassword=sonar --set persistence.storageClass=standard --set ingress.enabled=true
