- name: Configure EC2 Instance
  hosts: all
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3', 'python3-pip']
        state: present
    
    - name: Check if MicroK8s is installed
        become: true
        command: snap list | grep microk8s
        register: microk8s_check
        ignore_errors: yes
    
    - name: Install MicroK8s
      shell: |
        snap install microk8s --classic --channel=1.27
        usermod -a -G microk8s ubuntu
        sudo chown -f -R ubuntu ~/.kube

    - name: Wait for MicroK8s to start
      shell: microk8s status --wait-ready

    - name: Access Kubernetes
      shell: microk8s kubectl get nodes
      
    - name: Enable MicroK8s addons
      shell: microk8s enable dns storage ingress
      
    - name: Create .bash_aliases file if not exist
      file:
        path: /home/ubuntu/.bash_aliases
        state: touch
        owner: ubuntu
        group: ubuntu

    - name: Add kubectl alias
      lineinfile:
        dest: /home/ubuntu/.bash_aliases
        line: "alias kubectl='microk8s kubectl'"
        create: yes
        owner: ubuntu
        group: ubuntu
      become_user: ubuntu


