- name: Configure EC2 Instance
  hosts: all
  become: true
  vars:
    microk8s_version: "1.27"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3', 'python3-pip']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Helm
      apt:
        name: ['helm']
        state: present


    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install MicroK8s
      shell: |
        snap install microk8s --classic --channel={{ microk8s_version }}
        usermod -a -G microk8s ubuntu
      environment:
        HOME: /home/ubuntu

    - name: Wait for MicroK8s to start
      shell: microk8s.status --wait-ready
      environment:
        HOME: /home/ubuntu

    - name: Enable MicroK8s addons
      shell: microk8s.enable dns storage ingress
      environment:
        HOME: /home/ubuntu

    - name: Create .bash_aliases file if not exist
      file:
        path: /home/ubuntu/.bash_aliases
        state: touch
        owner: ubuntu
        group: ubuntu

    - name: Add kubectl alias
      lineinfile:
        dest: /home/ubuntu/.bash_aliases
        line: "alias kubectl='microk8s kubectl'"
        create: yes
        owner: ubuntu
        group: ubuntu
      become_user: ubuntu


- name: Deploy SonarQube
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install Helm
      apt:
        name: ['helm']
        state: present

    - name: Add SonarQube Helm repository
      shell: helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube

    - name: Upgrade or Install SonarQube
      shell: helm upgrade --install sonarqube sonarqube/sonarqube --set sonar.web.port=80 --set sonar.web.context=/ --set sonar.web.javaOpts="-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError" --set postgresql.postgresqlUsername=sonar --set postgresql.postgresqlPassword=sonar --set persistence.storageClass=standard --set ingress.enabled=true
